variable "AWS_REGION" {}
variable "AWS_ACCESS_KEY" {}
variable "AWS_SECRET_KEY" {}
variable "MAGENTO_INSTANCE_AMI" {}
variable "ssh_key_name" {}
variable "magento_ec2_sg" {}
variable "private_subnet_1" {}
variable "private_subnet_2" {}
variable "private_subnet_3" {}
variable "target_group_arn" {}
variable "magento_instance_role" {}